#!/usr/bin/env bash
# PACER VPS bootstrap - Ubuntu 22.04 / 24.04.
#
# Idempotent. Run as root or with sudo:
#     bash deploy/install.sh <hostname> <letsencrypt-email>
#
# Example:
#     bash deploy/install.sh pacer.1commercesolutions.com keith@1commercesolutions.com
#
# What it does:
#   1. Installs Docker Engine + Compose plugin from Docker's official repo.
#   2. Adds 2GB swap if no swap is configured (small VPS plans run out of RAM
#      during builds).
#   3. Configures UFW: 22 (ssh) + 80/443. Default deny inbound.
#   4. Enables docker.service to start at boot.
#   5. Writes /opt/pacer/.env stub with deploy-specific keys ONLY if missing.
#      Does NOT overwrite an existing one - paste your real .env on top.
#
# Safety notes:
#   - Doesn't change SSH config - set up keys before running this.
#   - Doesn't pull the repo. Clone /opt/pacer yourself; this script only
#     prepares the OS.
#
set -euo pipefail

HOSTNAME_ARG="${1:-}"
EMAIL="${2:-}"
INSTALL_DIR="${INSTALL_DIR:-/opt/pacer}"

if [[ -z "$HOSTNAME_ARG" || -z "$EMAIL" ]]; then
  echo "Usage: $0 <hostname> <letsencrypt-email>" >&2
  echo "  e.g. $0 pacer.1commercesolutions.com keith@1commercesolutions.com" >&2
  exit 1
fi

if [[ "$EUID" -ne 0 ]]; then
  echo "Re-running with sudo..." >&2
  exec sudo -E bash "$0" "$HOSTNAME_ARG" "$EMAIL"
fi

log()  { echo -e "\033[36m[install]\033[0m $*"; }
warn() { echo -e "\033[33m[warn]\033[0m $*" >&2; }

# --- 1. apt + base packages -----------------------------------------
log "Updating apt and installing base packages..."
export DEBIAN_FRONTEND=noninteractive
apt-get update -y
apt-get install -y --no-install-recommends \
  ca-certificates curl gnupg lsb-release ufw git unzip jq apache2-utils

# --- 2. Docker (official repo) --------------------------------------
if ! command -v docker >/dev/null 2>&1; then
  log "Installing Docker Engine..."
  install -m 0755 -d /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg \
    | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  chmod a+r /etc/apt/keyrings/docker.gpg
  echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
    https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" \
    > /etc/apt/sources.list.d/docker.list
  apt-get update -y
  apt-get install -y docker-ce docker-ce-cli containerd.io \
                     docker-buildx-plugin docker-compose-plugin
else
  log "Docker already installed: $(docker --version)"
fi

systemctl enable --now docker

# --- 3. swap (small VPS protection) ---------------------------------
if ! swapon --show | grep -q '/swapfile'; then
  log "Adding 2GB swapfile..."
  fallocate -l 2G /swapfile || dd if=/dev/zero of=/swapfile bs=1M count=2048
  chmod 600 /swapfile
  mkswap /swapfile
  swapon /swapfile
  if ! grep -q '^/swapfile' /etc/fstab; then
    echo "/swapfile none swap sw 0 0" >> /etc/fstab
  fi
else
  log "Swap already configured."
fi
sysctl -w vm.swappiness=10 >/dev/null
echo "vm.swappiness=10" > /etc/sysctl.d/99-pacer.conf

# --- 4. UFW ---------------------------------------------------------
log "Configuring UFW (default deny inbound, allow 22/80/443)..."
ufw --force reset
ufw default deny incoming
ufw default allow outgoing
ufw allow 22/tcp comment 'ssh'
ufw allow 80/tcp comment 'http'
ufw allow 443/tcp comment 'https'
ufw --force enable
ufw status verbose

# --- 5. /opt/pacer scaffolding --------------------------------------
mkdir -p "$INSTALL_DIR"
cd "$INSTALL_DIR"

if [[ ! -f .env ]]; then
  log "Writing .env stub at $INSTALL_DIR/.env"
  cat > .env <<EOF
# Generated by deploy/install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Do NOT commit. Paste your real PACER secrets on top of this stub.

PACER_DOMAIN=$HOSTNAME_ARG
LETSENCRYPT_EMAIL=$EMAIL

# Generate the bcrypt hash with:
#   docker run --rm caddy:2-alpine caddy hash-password --plaintext '<pw>'
PACER_BASIC_USER=keith
PACER_BASIC_HASH=

ENVIRONMENT=production
LOG_LEVEL=INFO
EOF
  chmod 600 .env
  warn "Stub .env written. Paste your real secrets BEFORE bringing the stack up."
else
  log ".env already exists - leaving it alone."
fi

mkdir -p logs backups

cat <<NEXT

--------------------------------------------------------------------
  PACER VPS bootstrap complete.

  Next:
    1) cd $INSTALL_DIR
    2) git clone https://github.com/ksksrbiz-arch/PACER.git . # or rsync
    3) edit .env  - paste your real secrets, generate PACER_BASIC_HASH:
         docker run --rm caddy:2-alpine caddy hash-password --plaintext '<pw>'
    4) docker compose -f docker-compose.yml -f deploy/docker-compose.caddy.yml up -d --build
    5) docker compose exec pacer alembic upgrade head
    6) curl -fsS https://$HOSTNAME_ARG/  -> 401 (basic auth gate)

  DNS:  point an A record for $HOSTNAME_ARG to this VPS's public IPv4
        BEFORE step 4 (Caddy needs it to issue the cert).

--------------------------------------------------------------------
NEXT
